---
  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - mc
      - ncdu
      - htop
      - vim
      - python-setuptools
      - python-pip
    become: true

  - name: install pip docker
    pip: 
      name: docker

  - name: install pip docker-compose
    pip: 
      name: docker-compose

  - name: create project dir
    file:
      path: /{{ project_name }}
      state: directory
      mode: 0755
    become: true
